//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPC_Rental.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NEWS
    {
        public int ID { get; set; }
        public string NewImages { get; set; }
        public string Head { get; set; }
        public string ShortDescription { get; set; }
        public string Content { get; set; }
        public Nullable<int> User_ID { get; set; }
        public string DetailImages { get; set; }
        public Nullable<System.DateTime> Create_at { get; set; }
    
        public virtual USER USER { get; set; }
    }
}
