//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPC_Rental.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class USER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public USER()
        {
            this.ABOUTs = new HashSet<ABOUT>();
            this.NEWS = new HashSet<NEWS>();
            this.PROPERTies = new HashSet<PROPERTY>();
            this.PROPERTies1 = new HashSet<PROPERTY>();
        }
    
        public int ID { get; set; }
        [Display(Name = "Email")]
        [EmailAddress(ErrorMessage = "Yêu cầu nhập đúng định dạng email")]
        [Required(ErrorMessage = "Yêu cầu nhập Email")]
        public string Email { get; set; }



        [Display(Name = "Password")]
        [Required(ErrorMessage = "Yêu cầu nhập Password")]
        public string Password { get; set; }
        public string FullName { get; set; }
        public string Phone { get; set; }
        public string Address { get; set; }
        public string Role { get; set; }
        public Nullable<bool> Status { get; set; }
        //[Required]
        //public string PasswordNew { get; set; }
        //[Required]
        //[Display(Name = "Confirm Password")]
        //[Compare("PasswordNew", ErrorMessage = "Xác nhận mật khẩu không đúng")]
        //public string ConfirmPassword { set; get; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ABOUT> ABOUTs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NEWS> NEWS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROPERTY> PROPERTies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROPERTY> PROPERTies1 { get; set; }
    }
}
