// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.2.0.0
//      SpecFlow Generator Version:2.2.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace PPC_Rental.AcceptanceTests.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.2.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute()]
    public partial class UC03_ViewDetailOfProjectFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private Microsoft.VisualStudio.TestTools.UnitTesting.TestContext _testContext;
        
#line 1 "UC03_ViewDetailOfProject.feature"
#line hidden
        
        public virtual Microsoft.VisualStudio.TestTools.UnitTesting.TestContext TestContext
        {
            get
            {
                return this._testContext;
            }
            set
            {
                this._testContext = value;
            }
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassInitializeAttribute()]
        public static void FeatureSetup(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext testContext)
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner(null, 0);
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "UC03_ViewDetailOfProject", "\tAs a potential customer\r\n\tI want to see the details of a property\r\n\tSo that I ca" +
                    "n better decide to buy it.", ProgrammingLanguage.CSharp, new string[] {
                        "automated",
                        "web"});
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupAttribute()]
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestInitializeAttribute()]
        public virtual void TestInitialize()
        {
            if (((testRunner.FeatureContext != null) 
                        && (testRunner.FeatureContext.FeatureInfo.Title != "UC03_ViewDetailOfProject")))
            {
                global::PPC_Rental.AcceptanceTests.Features.UC03_ViewDetailOfProjectFeature.FeatureSetup(null);
            }
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCleanupAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Microsoft.VisualStudio.TestTools.UnitTesting.TestContext>(TestContext);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 8
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "PropertyName",
                        "Avatar",
                        "Images",
                        "Property Type",
                        "Content",
                        "Street",
                        "Ward",
                        "District",
                        "Price",
                        "UnitPrice",
                        "Area",
                        "BedRoom",
                        "BathRoom",
                        "ParkingPlace",
                        "Owner",
                        "Created_at",
                        "Created_post",
                        "Status",
                        "Note",
                        "Updated_at"});
            table1.AddRow(new string[] {
                        "PIS Top Apartment 1",
                        "1.png",
                        "test.jpg,",
                        "Apartment",
                        "The surrounding neighborhood is very much localized with a great number of local " +
                            "shops",
                        "Điền Viên Thôn",
                        "TT Tây Đằng",
                        "Ba Vì",
                        "10000",
                        "USD",
                        "120m2",
                        "3",
                        "3",
                        "1",
                        "lythihuyenchau@gmail.com",
                        "2017-11-09",
                        "2017-11-09",
                        "Đã duyệt",
                        "Done",
                        "2017-11-09"});
            table1.AddRow(new string[] {
                        "PIS Top Apartment 2",
                        "2.png",
                        "test.jpg,",
                        "Apartment",
                        "The surrounding neighborhood is very much localized with a great number of local " +
                            "shops",
                        "Điền Viên Thôn",
                        "TT Tây Đằng",
                        "Ba Vì",
                        "10000",
                        "USD",
                        "120m2",
                        "3",
                        "3",
                        "1",
                        "lythihuyenchau@gmail.com",
                        "2017-11-09",
                        "2017-11-09",
                        "Đã duyệt",
                        "Done",
                        "2017-11-09"});
            table1.AddRow(new string[] {
                        "PIS Top Apartment 3",
                        "3.png",
                        "test.jpg,",
                        "Apartment",
                        "The surrounding neighborhood is very much localized with a great number of local " +
                            "shops",
                        "Điền Viên Thôn",
                        "TT Tây Đằng",
                        "Ba Vì",
                        "10000",
                        "USD",
                        "120m2",
                        "3",
                        "3",
                        "1",
                        "lythihuyenchau@gmail.com",
                        "2017-11-09",
                        "2017-11-09",
                        "Đã duyệt",
                        "Done",
                        "2017-11-09"});
#line 9
 testRunner.Given("the following properties", ((string)(null)), table1, "Given ");
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("The propertyname,the avatar,owner,content,price of a property can be seen")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "UC03_ViewDetailOfProject")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("automated")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("web")]
        public virtual void ThePropertynameTheAvatarOwnerContentPriceOfAPropertyCanBeSeen()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("The propertyname,the avatar,owner,content,price of a property can be seen", ((string[])(null)));
#line 15
this.ScenarioSetup(scenarioInfo);
#line 8
this.FeatureBackground();
#line 16
 testRunner.When("I open the details of \'PIS Top Apartment 1\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "PropertyName",
                        "Avatar",
                        "Owner",
                        "Price",
                        "Content"});
            table2.AddRow(new string[] {
                        "PIS Top Apartment 1",
                        "1.png",
                        "lythihuyenchau@gmail.com",
                        "10000",
                        "The surrounding neighborhood is very much localized with a great number of local " +
                            "shops"});
#line 17
 testRunner.Then("the property details should show", ((string)(null)), table2, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
